ALTER TABLE "CmsImageEntry"
ADD COLUMN "draftCropX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "draftCropY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "publishedCropX" DOUBLE PRECISION,
ADD COLUMN "publishedCropY" DOUBLE PRECISION;
