import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { prisma } from "@/lib/prisma";
import type { PermissionKey } from "@/modules/auth/permissions/permission-catalog";
import type { AppUserRole } from "@/modules/auth/roles";
import { CashExpenseAttachmentUpload } from "@/modules/operations/components/cash-expense-attachment-upload";
import { CashFundAdminActions } from "@/modules/operations/components/cash-fund-admin-actions";
import { cancelCashExpenseReportAction, decideCashExpenseReportAction, submitCashExpenseReportAction } from "@/modules/operations/server/cash-fund.actions";
import { listCashFundCategories, listCashFundConfiguration, listCashFundGroupsWithBudget, listCashFundReportsForReview, listTeacherCashExpenseReports, listTeacherCashFundGroups } from "@/modules/operations/server/cash-fund.repository";

type Props = { user: { id: string; role: AppUserRole; permissionKeys: PermissionKey[] } };
type ReactFormAction = (formData: FormData) => void | Promise<void>;
const fieldClass = "h-9 rounded-md border border-slate-300 bg-white px-3 text-sm";
const formAction = (action: (...args: never[]) => Promise<unknown>) => action as unknown as ReactFormAction;
const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });
const balanceOf = (entries: Array<{ amount: unknown }>) => entries.reduce((total, entry) => total + Number(entry.amount), 0);

export async function CashFundDashboardView({ user }: Props) {
  const isTeacher = user.role === "TEACHER" || user.role === "ADMIN_TEACHER";
  const canOperate = user.permissionKeys.includes("cash-fund.operate");
  const canConfigure = user.permissionKeys.includes("cash-fund.configure");

  if (!isTeacher) {
    const [groups, settings, reports] = await Promise.all([listCashFundGroupsWithBudget(), listCashFundConfiguration(), canOperate ? listCashFundReportsForReview() : Promise.resolve([])]);
    const rows = groups.map((group) => ({ id: group.id, name: group.name, budget: Number(group.cashFundBudget?.amountPerPeriod ?? 0), balance: balanceOf(group.cashFundEntries), teachers: group.teacherResponsibilities.map(({ teacher }) => teacher.displayName), pendingCount: group.cashExpenseReports.length, pendingAmount: group.cashExpenseReports.reduce((total, report) => total + Number(report.requestedAmount), 0) }));
    const generalBalance = rows.reduce((total, row) => total + row.balance, 0);
    const frequency = settings?.renewalFrequency ?? "MONTHLY";
    const renewalLabel = frequency === "WEEKLY" ? "semanal" : frequency === "BIWEEKLY" ? "quincenal" : "mensual";
    return <div className="flex w-full flex-col gap-4">
      <header><h1 className="text-2xl font-semibold text-slate-900">Caja chica</h1><p className="mt-1 text-sm text-slate-600">Fondos compartidos por grupo y docentes asignados.</p></header>
      <Card><CardContent className="grid gap-5 p-5 sm:p-6 md:grid-cols-[minmax(0,1fr)_auto] md:items-end"><div><p className="text-sm font-medium text-slate-500">Saldo general disponible</p><p className="mt-1 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{money.format(generalBalance)}</p><dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3 text-sm sm:flex sm:flex-wrap"><div><dt className="text-slate-500">Grupos activos</dt><dd className="font-semibold">{rows.length}</dd></div><div><dt className="text-slate-500">Renovación</dt><dd className="font-semibold">{renewalLabel}</dd></div><div><dt className="text-slate-500">Rendiciones pendientes</dt><dd className="font-semibold">{reports.length || rows.reduce((total, row) => total + row.pendingCount, 0)}</dd></div></dl></div>{canOperate || canConfigure ? <CashFundAdminActions groups={rows.map((row) => ({ id: row.id, name: row.name, amountPerPeriod: row.budget || null }))} renewalFrequency={frequency} canOperate={canOperate} canConfigure={canConfigure} /> : null}</CardContent></Card>
      <Card><CardHeader><CardTitle>Presupuesto por grupo</CardTitle></CardHeader><CardContent>{rows.length ? <div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Grupo</TableHead><TableHead>Docentes habilitados</TableHead><TableHead>Presupuesto por período</TableHead><TableHead>Rendiciones pendientes</TableHead><TableHead className="text-right">Saldo</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.name}</TableCell><TableCell>{row.teachers.join(", ") || "Sin docentes asignados"}</TableCell><TableCell>{row.budget ? money.format(row.budget) : "Sin configurar"}</TableCell><TableCell>{row.pendingCount} · {money.format(row.pendingAmount)}</TableCell><TableCell className="text-right font-semibold">{money.format(row.balance)}</TableCell></TableRow>)}</TableBody></Table></div> : <p className="py-8 text-center text-sm text-slate-500">No hay grupos activos.</p>}</CardContent></Card>
      {canOperate ? <Card><CardHeader><CardTitle>Rendiciones para revisar</CardTitle></CardHeader><CardContent className="space-y-4">{reports.length ? reports.map((report) => <article key={report.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-medium">{report.concept}</p><p className="text-sm text-slate-600">{report.group?.name} · {report.teacher.displayName} · {money.format(Number(report.requestedAmount))}</p><p className="mt-1 text-xs text-slate-500">{report.justification}</p></div>{report.attachments.length ? <div className="text-xs">{report.attachments.map((attachment) => <a key={attachment.id} href={attachment.url} target="_blank" className="block text-blue-700 underline">{attachment.fileName}</a>)}</div> : null}</div><form action={formAction(decideCashExpenseReportAction)} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="reportId" value={report.id} /><label className="grid gap-1 text-xs">Monto aprobado<input className={fieldClass} name="approvedAmount" type="number" min="0" max={Number(report.requestedAmount)} step="0.01" defaultValue={Number(report.requestedAmount)} required /></label><label className="grid min-w-52 flex-1 gap-1 text-xs">Motivo si hay diferencia<input className={fieldClass} name="reason" maxLength={500} /></label><Button type="submit">Resolver</Button></form></article>) : <p className="text-sm text-slate-500">No hay rendiciones pendientes.</p>}</CardContent></Card> : null}
    </div>;
  }

  const teacher = await prisma.teacherProfile.findUnique({ where: { userId: user.id }, select: { id: true, isActive: true } });
  if (!teacher?.isActive) return null;
  const [categories, groups, reports] = await Promise.all([listCashFundCategories(), listTeacherCashFundGroups(teacher.id), listTeacherCashExpenseReports(teacher.id)]);
  return <div className="flex w-full flex-col gap-4"><header><h1 className="text-2xl font-semibold text-slate-900">Caja chica</h1><p className="mt-1 text-sm text-slate-600">Usá el fondo compartido del grupo que corresponda.</p></header><section className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Enviar rendición</CardTitle></CardHeader><CardContent><form action={formAction(submitCashExpenseReportAction)} className="grid gap-2"><select className={fieldClass} name="groupId" required><option value="">Grupo y saldo disponible</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name} · {money.format(balanceOf(group.cashFundEntries))}</option>)}</select><select className={fieldClass} name="categoryId" required><option value="">Categoría</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input className={fieldClass} name="amount" type="number" min="0.01" step="0.01" placeholder="Monto" required /><input className={fieldClass} name="concept" placeholder="Concepto" required /><textarea className="rounded-md border border-slate-300 p-3 text-sm" name="justification" placeholder="Justificación" required /><input className={fieldClass} name="expenseDate" type="date" required /><Button type="submit" disabled={!groups.length}>Enviar rendición</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Mis rendiciones</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{reports.length ? reports.map((report) => <article key={report.id} className="space-y-2 border-t pt-3 first:border-0 first:pt-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{report.concept}</p><p className="text-slate-600">{report.group?.name} · {report.category.name} · {money.format(Number(report.requestedAmount))} · {report.status}</p></div>{report.status === "PENDING" ? <form action={formAction(cancelCashExpenseReportAction.bind(null, report.id))}><Button size="sm" type="submit" variant="outline">Cancelar</Button></form> : null}</div>{report.status === "PENDING" ? <CashExpenseAttachmentUpload reportId={report.id} /> : null}{report.decisionReason ? <p className="text-xs text-slate-500">{report.decisionReason}</p> : null}</article>) : <p className="text-slate-500">Todavía no hay rendiciones.</p>}</CardContent></Card></section></div>;
}
