import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { prisma } from "@/lib/prisma";
import type { PermissionKey } from "@/modules/auth/permissions/permission-catalog";
import type { AppUserRole } from "@/modules/auth/roles";
import { InventoryAdminActions } from "@/modules/operations/components/inventory-admin-actions";
import { InventoryProductEditor } from "@/modules/operations/components/inventory-product-editor";
import { InventoryRequestDecisionForm } from "@/modules/operations/components/inventory-request-decision-form";
import { InventoryRequestForm } from "@/modules/operations/components/inventory-request-form";
import { cancelInventoryRequestAction, decideInventoryRequestLineAction, reverseInventoryMovementAction } from "@/modules/operations/server/inventory.actions";
import { listInventoryMovementsForAdmin, listInventoryProductsBelowMinimum, listInventoryProductsWithStock, listInventoryRequestsForReview, listTeacherInventoryRequests } from "@/modules/operations/server/inventory.repository";

type Props = { user: { id: string; role: AppUserRole; permissionKeys: PermissionKey[] } };
type ReactFormAction = (formData: FormData) => void | Promise<void>;
const fieldClass = "h-9 rounded-md border border-slate-300 bg-white px-3 text-sm";
const formAction = (action: (...args: never[]) => Promise<unknown>) => action as unknown as ReactFormAction;
const movementLabels = { STOCK_IN: "Ingreso", REQUEST_FULFILLMENT: "Entrega", MANUAL_ADJUSTMENT: "Ajuste", REVERSAL: "Reversión" } as const;

export async function InventoryDashboardView({ user }: Props) {
  const canOperate = user.permissionKeys.includes("inventory.operate");
  const canConfigure = user.permissionKeys.includes("inventory.configure");
  const teacher = await prisma.teacherProfile.findUnique({ where: { userId: user.id }, select: { id: true } });

  if (canOperate || canConfigure) {
    const [products, lowStock, pendingRequests, movements] = await Promise.all([listInventoryProductsWithStock(), listInventoryProductsBelowMinimum(), listInventoryRequestsForReview(), listInventoryMovementsForAdmin()]);
    const totalStock = products.reduce((total, product) => total + product.stock, 0);
    return <div className="flex w-full flex-col gap-4">
      <header><h1 className="text-2xl font-semibold text-slate-900">Inventario</h1><p className="mt-1 text-sm text-slate-600">Vista general de productos, stock y solicitudes.</p></header>
      <Card><CardContent className="grid gap-5 p-5 sm:p-6 md:grid-cols-[minmax(0,1fr)_auto] md:items-end"><div><p className="text-sm font-medium text-slate-500">Stock disponible</p><p className="mt-1 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{totalStock.toLocaleString("es-AR", { maximumFractionDigits: 3 })}</p><dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3 text-sm sm:flex sm:flex-wrap"><div><dt className="text-slate-500">Productos registrados</dt><dd className="font-semibold text-slate-900">{products.length}</dd></div><div><dt className="text-slate-500">Alertas de stock</dt><dd className={lowStock.length ? "font-semibold text-amber-700" : "font-semibold text-slate-900"}>{lowStock.length}</dd></div><div><dt className="text-slate-500">Solicitudes pendientes</dt><dd className="font-semibold text-slate-900">{pendingRequests.length}</dd></div></dl></div><InventoryAdminActions canOperate={canOperate} canConfigure={canConfigure} products={products.map((product) => ({ id: product.id, name: product.name, unit: product.unit, stock: product.stock, minimumStock: Number(product.minimumStock) }))} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Stock por producto</CardTitle></CardHeader><CardContent>{products.length ? <><div className="space-y-3 md:hidden">{products.map((product) => { const low = product.stock <= Number(product.minimumStock); return <article key={product.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><InventoryProductEditor product={{ id: product.id, name: product.name, unit: product.unit, stock: product.stock, minimumStock: Number(product.minimumStock) }} trigger={<button type="button" className="font-semibold text-slate-900 hover:underline" />}>{product.name}</InventoryProductEditor><p className="mt-1 text-xs text-slate-500">Mínimo esperado: {Number(product.minimumStock)} {product.unit}</p></div><p className={low ? "font-semibold text-amber-700" : "font-semibold text-slate-950"}>{product.stock} {product.unit}</p></div><p className={low ? "mt-3 text-sm text-amber-700" : "mt-3 text-sm text-emerald-700"}>{low ? "Requiere reposición" : "Stock disponible"}</p></article>; })}</div><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Stock mínimo</TableHead><TableHead className="text-right">Disponible</TableHead><TableHead className="text-right">Estado</TableHead></TableRow></TableHeader><TableBody>{products.map((product) => { const low = product.stock <= Number(product.minimumStock); return <TableRow key={product.id}><InventoryProductEditor product={{ id: product.id, name: product.name, unit: product.unit, stock: product.stock, minimumStock: Number(product.minimumStock) }} trigger={<TableCell className="cursor-pointer font-medium hover:bg-slate-50" />}>{product.name}<span className="block text-xs text-slate-500">Unidad: {product.unit}</span></InventoryProductEditor><TableCell>{Number(product.minimumStock)} {product.unit}</TableCell><TableCell className={low ? "text-right font-semibold text-amber-700" : "text-right font-semibold"}>{product.stock} {product.unit}</TableCell><TableCell className={low ? "text-right text-amber-700" : "text-right text-emerald-700"}>{low ? "Requiere reposición" : "Disponible"}</TableCell></TableRow>; })}</TableBody></Table></div></> : <p className="py-8 text-center text-sm text-slate-500">Todavía no hay productos registrados.</p>}</CardContent></Card>
      <section className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><Card><CardHeader><CardTitle>Solicitudes pendientes ({pendingRequests.length})</CardTitle></CardHeader><CardContent className="space-y-4 text-sm">{pendingRequests.length ? pendingRequests.map((request) => request.lines.length === 1 ? request.lines.map((line) => <form key={line.id} action={formAction(decideInventoryRequestLineAction)} className="grid gap-2 border-t pt-3 first:border-0 first:pt-0"><input type="hidden" name="lineId" value={line.id} /><p className="font-medium">{request.teacher.displayName} · {line.product.name}</p><p className="text-slate-600">Solicita {Number(line.requestedQuantity)} {line.product.unit}</p><input className={fieldClass} name="approvedQuantity" type="number" min="0" max={Number(line.requestedQuantity)} step="0.001" defaultValue={Number(line.requestedQuantity)} required /><input className={fieldClass} name="reason" placeholder="Motivo si hay diferencia" /><Button type="submit" variant="outline">Resolver solicitud</Button></form>) : <InventoryRequestDecisionForm key={request.id} requestId={request.id} teacherName={request.teacher.displayName} lines={request.lines.map((line) => ({ id: line.id, productName: line.product.name, requestedQuantity: Number(line.requestedQuantity) }))} />) : <p className="py-4 text-center text-slate-500">No hay solicitudes pendientes.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Alertas de stock ({lowStock.length})</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{lowStock.length ? lowStock.map((product) => <article key={product.id} className="border-t pt-3 first:border-0 first:pt-0"><p className="font-medium text-slate-900">{product.name}</p><p className="mt-1 text-slate-600">Disponible: <span className="font-semibold text-amber-700">{product.stock} {product.unit}</span> · mínimo {Number(product.minimumStock)} {product.unit}</p></article>) : <p className="py-4 text-center text-slate-500">No hay alertas de stock.</p>}</CardContent></Card></section>
      <Card><CardHeader><CardTitle>Historial de movimientos</CardTitle></CardHeader><CardContent className="space-y-4">{movements.length ? movements.map((movement) => <div key={movement.id} className="flex items-center justify-between gap-3 border-t pt-3 text-sm first:border-0 first:pt-0"><div><p className="font-medium text-slate-900">{movement.product.name} · {movementLabels[movement.type]}</p><p className="text-slate-600">{Number(movement.quantity)} {movement.product.unit} · {movement.reason ?? "Sin detalle"}</p></div>{movement.type !== "REVERSAL" && !movement.isReversed ? <form action={formAction(reverseInventoryMovementAction.bind(null, movement.id))}><Button size="sm" type="submit" variant="outline">Revertir</Button></form> : <span className="text-xs text-slate-500">{movement.isReversed ? "Revertido" : "Reversión"}</span>}</div>) : <p className="py-4 text-center text-sm text-slate-500">Todavía no hay movimientos.</p>}</CardContent></Card>
    </div>;
  }

  if (!teacher) return null;
  const [products, requests] = await Promise.all([listInventoryProductsWithStock(), listTeacherInventoryRequests(teacher.id)]);
  return <div className="flex w-full flex-col gap-4"><header><h1 className="text-2xl font-semibold text-slate-900">Inventario</h1><p className="mt-1 text-sm text-slate-600">Solicitá los productos que necesitás y seguí tus pedidos.</p></header><section className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Solicitar productos</CardTitle></CardHeader><CardContent><InventoryRequestForm products={products.map((product) => ({ id: product.id, name: product.name, unit: product.unit, stock: product.stock }))} /></CardContent></Card><Card><CardHeader><CardTitle>Mis solicitudes</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{requests.length ? requests.map((request) => <article key={request.id} className="space-y-2 border-t pt-3 first:border-0 first:pt-0"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">Pedido {request.id.slice(-6)} · {request.status}</p>{request.lines.map((line) => <p key={line.id} className="text-slate-600">{line.product.name}: {Number(line.requestedQuantity)} {line.product.unit}{line.approvedQuantity !== null ? ` · aprobado ${Number(line.approvedQuantity)}` : ""}</p>)}</div>{request.status === "PENDING" ? <form action={formAction(cancelInventoryRequestAction.bind(null, request.id))}><Button size="sm" type="submit" variant="outline">Cancelar</Button></form> : null}</div>{request.decisionReason ? <p className="text-xs text-slate-500">{request.decisionReason}</p> : null}</article>) : <p className="py-4 text-center text-slate-500">Todavía no hay solicitudes.</p>}</CardContent></Card></section></div>;
}


