ALTER TABLE "CmsImageEntry"
  ADD COLUMN "draftMarginX" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "draftMarginY" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "publishedMarginX" DOUBLE PRECISION,
  ADD COLUMN "publishedMarginY" DOUBLE PRECISION;
