ALTER TABLE "CmsImageEntry"
  ADD COLUMN "draftZoom" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN "draftFitMode" TEXT NOT NULL DEFAULT 'COVER',
  ADD COLUMN "draftFrameSize" TEXT NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN "publishedZoom" DOUBLE PRECISION,
  ADD COLUMN "publishedFitMode" TEXT,
  ADD COLUMN "publishedFrameSize" TEXT;