import { DocumentStatus } from "@prisma/client";
import { Download, FileText, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DocumentUploadForm } from "@/modules/documents/components/document-upload-form";
import { deleteDocumentAction, setDocumentStatusAction } from "@/modules/documents/server/document.actions";
import { listDocuments } from "@/modules/documents/server/document.repository";
function date(value: Date) { return value.toLocaleDateString("es-AR", { day: "2-digit", month: "2-digit", year: "numeric" }); }
function size(value: number) { return `${(value / 1024 / 1024).toFixed(value >= 1024 * 1024 ? 1 : 2)} MB`; }
export async function DashboardDocumentsView({ ok, error }: { ok?: string; error?: string }) {
  const documents = await listDocuments();
  return <div className="space-y-4 [font-family:var(--font-montserrat)]">{ok ? <p className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800">{ok}</p> : null}{error ? <p className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p> : null}<Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-4 w-4" />Subir documento</CardTitle><p className="text-sm text-muted-foreground">Los PDFs publicados quedan disponibles con un enlace estable de Koru.</p></CardHeader><CardContent><DocumentUploadForm /></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Documentos cargados</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Documento</TableHead><TableHead>Estado</TableHead><TableHead>Actualizado</TableHead><TableHead>Enlace</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{documents.length === 0 ? <TableRow><TableCell colSpan={5} className="text-muted-foreground">Todavía no hay documentos.</TableCell></TableRow> : documents.map((document) => <TableRow key={document.id}><TableCell><p className="font-medium text-foreground">{document.title}</p><p className="text-xs text-muted-foreground">{document.originalFileName} · {size(document.sizeBytes)}</p></TableCell><TableCell><Badge variant={document.status === DocumentStatus.PUBLISHED ? "default" : "secondary"}>{document.status === DocumentStatus.PUBLISHED ? "Publicado" : "Borrador"}</Badge></TableCell><TableCell className="text-sm text-muted-foreground">{date(document.updatedAt)}</TableCell><TableCell><a href={`/documentos/${document.slug}`} target="_blank" className="text-sm text-primary hover:underline">/documentos/{document.slug}</a></TableCell><TableCell><div className="flex justify-end gap-1.5"><a href={`/documentos/${document.slug}`} target="_blank" aria-label={`Descargar ${document.title}`}><Button type="button" variant="outline" size="icon-sm"><Download /></Button></a><form action={setDocumentStatusAction}><input type="hidden" name="id" value={document.id} /><input type="hidden" name="status" value={document.status === DocumentStatus.PUBLISHED ? "DRAFT" : "PUBLISHED"} /><Button type="submit" variant="outline">{document.status === DocumentStatus.PUBLISHED ? "Despublicar" : "Publicar"}</Button></form><form action={deleteDocumentAction}><input type="hidden" name="id" value={document.id} /><Button type="submit" variant="destructive" size="icon-sm" aria-label={`Eliminar ${document.title}`}><Trash2 /></Button></form></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}
